apiVersion: v1
kind: Service
metadata:
  name: contacts
  namespace: contactfis-dev
  labels:
    app: contacts
spec:
  type: ClusterIP
  selector:
    app: contacts
  ports:
    - name: http
      port: 3000      # service port
      targetPort: 3000